### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by gamecubate** [dbanay/Smalltalk#12]
This is really neat.

Launched like a charm on macOS once this, in osx/Makefile:
```
SDL_CFLAG := $(shell sdl2-config --cflags)
```

was replaced by that:
```
SDL_CFLAG := $(shell sdl2-config --cflags | sed 's/\/SDL2//')
```

Thanks!

**Comment by artkiver** [comment]
This rectifies build issues I encountered using libsdl from MacPorts as well.

Perhaps it would be better submitted as a Pull Request so that it can be merged?

https://github.com/dbanay/Smalltalk/issues/10 seems as if it is probably related as well, though I do not use homebrew, so I cannot comment whether the above recommendation is copasetic for all macOS port managers, it seems plausible.

**Comment by gamecubate** [comment]
@dbanay seems AWOL. Not sure it's worth it. A fork, perhaps? Or -- my favourite option nowadays -- let's wait and see and either move on, some day, or be delighted at an earlier one. :)

**Comment by dbanay** [comment]
This is great. Can you submit a pull request?  Thanks

**Comment by gamecubate** [comment]
@dbanay done, for your review [and merge].
@artkiver Thanks for the nudge. :)
